/** img_to_header - convert image files to C++ header with base64 + memfd
 *  Usage: img_to_header <output.h> <img1> [img2...]
 *  Build: clang++ -std=c++17 -O2 img_to_header.cpp -o img_to_header
 */
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>

static const char kBase64[] =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

static std::string base64Encode(const std::vector<unsigned char>& data) {
    std::string out;
    out.reserve((data.size() + 2) / 3 * 4);
    for (size_t i = 0; i < data.size(); i += 3) {
        unsigned n = (unsigned)data[i] << 16;
        if (i + 1 < data.size()) n |= (unsigned)data[i + 1] << 8;
        if (i + 2 < data.size()) n |= (unsigned)data[i + 2];
        out += kBase64[(n >> 18) & 63];
        out += kBase64[(n >> 12) & 63];
        out += (i + 1 < data.size()) ? kBase64[(n >> 6) & 63] : '=';
        out += (i + 2 < data.size()) ? kBase64[n & 63] : '=';
    }
    return out;
}

static std::string basenameNoExt(const std::string& path) {
    auto pos = path.rfind('/');
    std::string name = (pos != std::string::npos) ? path.substr(pos + 1) : path;
    for (auto& c : name) if (c == '.' || c == '-') c = '_';
    return name;
}

int main(int argc, char** argv) {
    if (argc < 3) {
        std::cerr << "Usage: img_to_header <output.h> <img1> [img2...]" << std::endl;
        return 1;
    }

    std::string outPath = argv[1];
    std::ofstream out(outPath);
    if (!out) { std::cerr << "Cannot open: " << outPath << std::endl; return 1; }

    std::string guard;
    for (char c : outPath) guard += (c == '.' || c == '/' ? '_' : (char)toupper(c));

    out << "// Auto-generated by img_to_header - do not edit\n";
    out << "// Embedded images via base64 + memfd (zero file dependencies)\n";
    out << "#ifndef " << guard << "\n#define " << guard << "\n\n";
    out << "#include <sys/mman.h>\n#include <unistd.h>\n";
    out << "#include <cstring>\n#include <cstdio>\n\n";

    // Base64 decoder
    out << "static const signed char kImgDec[256] = {\n";
    for (int i = 0; i < 256; i++) {
        if (i % 16 == 0) out << "    ";
        int v = -1;
        if (i >= 'A' && i <= 'Z') v = i - 'A';
        else if (i >= 'a' && i <= 'z') v = i - 'a' + 26;
        else if (i >= '0' && i <= '9') v = i - '0' + 52;
        else if (i == '+') v = 62;
        else if (i == '/') v = 63;
        out << v << (i < 255 ? "," : "");
        if (i % 16 == 15) out << "\n";
    }
    out << "};\n\n";

    // Decode + memfd helper
    out << "inline size_t ImgDecode(const char* s, unsigned char* d, size_t m) {\n";
    out << "    size_t di=0; int val=0, vb=-8;\n";
    out << "    while (*s && di<m) {\n";
    out << "        int c=kImgDec[(unsigned char)*s++]; if(c==-1)continue;\n";
    out << "        val=(val<<6)|c; vb+=6;\n";
    out << "        if(vb>=0){d[di++]=(unsigned char)((val>>vb)&0xFF); vb-=8;}\n";
    out << "    }\n    return di;\n}\n\n";

    out << "inline DString ImgMemFd(const char* b64, const char* tag) {\n";
    out << "    int fd=memfd_create(tag, MFD_CLOEXEC);\n";
    out << "    if(fd<0) return _T(\"\");\n";
    out << "    unsigned char buf[8192];\n";
    out << "    size_t len=ImgDecode(b64,buf,sizeof(buf));\n";
    out << "    if(write(fd,buf,len)!=(ssize_t)len){close(fd);return _T(\"\");}\n";
    out << "    char tmp[32]; snprintf(tmp,sizeof(tmp),\"%d\",fd);\n";
    out << "    DString p=_T(\"/proc/self/fd/\");\n";
    out << "    for(char* x=tmp;*x;x++) p+=(DString::value_type)(unsigned char)*x;\n";
    out << "    return p;\n}\n\n";

    // Process each image
    for (int i = 2; i < argc; i++) {
        std::ifstream f(argv[i], std::ios::binary);
        if (!f) { std::cerr << "Cannot open: " << argv[i] << std::endl; return 1; }
        std::vector<unsigned char> data((std::istreambuf_iterator<char>(f)),
                                         std::istreambuf_iterator<char>());
        std::string name = basenameNoExt(argv[i]);
        std::string b64 = base64Encode(data);
        std::string cap = name;
        if (!cap.empty()) cap[0] = (char)toupper(cap[0]);

        out << "// " << argv[i] << " (" << data.size() << " bytes)\n";
        out << "static const char kImg_" << name << "[] =\n";
        for (size_t j = 0; j < b64.size(); j += 72) {
            out << "    \"" << b64.substr(j, 72) << "\""
                << (j + 72 >= b64.size() ? ";\n" : "\n");
        }
        out << "inline DString GetEmbedded" << cap << "Path() {\n";
        out << "    static DString p;\n";
        out << "    if(p.empty()) p=ImgMemFd(kImg_" << name << ",\"" << name << "\");\n";
        out << "    return p;\n}\n\n";
    }

    out << "#endif\n";
    std::cout << "Generated " << outPath << " with " << (argc - 2) << " images" << std::endl;
    return 0;
}
