#!/usr/bin/env python3
"""Convert XML theme files to C++ header string constants.

Usage: python3 xml_to_header.py <output_header> <input_xml_files...>

Generates a header with const char* string constants for each XML file.
The strings are null-terminated and can be used directly with GetSkinFile().
"""
import sys
import os

def escape_c_string(text):
    result = []
    for ch in text:
        if ch == '\\':
            result.append('\\\\')
        elif ch == '"':
            result.append('\\"')
        elif ch == '\n':
            result.append('\\n')
        elif ch == '\r':
            result.append('')
        elif ch == '\t':
            result.append('\\t')
        else:
            result.append(ch)
    return ''.join(result)

def xml_to_header(output_path, input_files):
    guard = os.path.basename(output_path).replace('.', '_').upper()

    lines = []
    lines.append('// Auto-generated by xml_to_header.py - do not edit')
    lines.append(f'#ifndef {guard}')
    lines.append(f'#define {guard}')
    lines.append('')
    lines.append('#include "duilib/duilib_string.h"')
    lines.append('')
    lines.append('namespace ui_resources {')
    lines.append('')

    for fpath in input_files:
        with open(fpath, 'r', encoding='utf-8') as f:
            content = f.read()

        # Generate variable name from file path
        # e.g., "themes/default/basic/basic.xml" -> "basic_xml"
        name = os.path.basename(fpath).replace('.', '_')
        var_name = f"k_{name}"

        # Escape content and wrap in DString literal
        escaped = escape_c_string(content)
        lines.append(f'// Original: {fpath}')
        lines.append(f'static const DString {var_name} = _T("{escaped}");')
        lines.append('')

    lines.append('} // namespace ui_resources')
    lines.append('')
    lines.append(f'#endif // {guard}')

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f"Generated {output_path} with {len(input_files)} XML files")

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <output_header> <input_xml_files...>")
        sys.exit(1)
    xml_to_header(sys.argv[1], sys.argv[2:])
