/** xml_to_header - convert XML files to C++ header with DString constants
 *  Usage: xml_to_header <output_header> <input_xml_files...>
 *  Build: clang++ -std=c++17 -O2 xml_to_header.cpp -o xml_to_header
 */
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <sys/stat.h>

static std::string escapeString(const std::string& s) {
    std::string out;
    out.reserve(s.size());
    for (char ch : s) {
        switch (ch) {
        case '\\': out += "\\\\"; break;
        case '"':  out += "\\\""; break;
        case '\n': out += "\\n";  break;
        case '\r': /* skip */     break;
        case '\t': out += "\\t";  break;
        default:   out += ch;     break;
        }
    }
    return out;
}

static std::string basenameNoExt(const std::string& path) {
    auto pos = path.rfind('/');
    std::string name = (pos != std::string::npos) ? path.substr(pos + 1) : path;
    auto dot = name.rfind('.');
    if (dot != std::string::npos) name = name.substr(0, dot);
    for (auto& c : name) if (c == '.') c = '_';
    return name;
}

static std::string readFile(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) {
        std::cerr << "Error: cannot open " << path << std::endl;
        return "";
    }
    std::string content((std::istreambuf_iterator<char>(f)),
                         std::istreambuf_iterator<char>());
    return content;
}

int main(int argc, char** argv) {
    if (argc < 3) {
        std::cerr << "Usage: xml_to_header <output_header> <input_xml_files...>" << std::endl;
        return 1;
    }

    std::string outputPath = argv[1];
    std::vector<std::string> inputFiles;
    for (int i = 2; i < argc; i++) inputFiles.push_back(argv[i]);

    // Generate guard name
    std::string guard;
    auto pos = outputPath.rfind('/');
    std::string outName = (pos != std::string::npos) ? outputPath.substr(pos + 1) : outputPath;
    for (char& c : outName) { guard += (c == '.' ? '_' : toupper(c)); }

    // Write header
    std::ofstream out(outputPath);
    out << "// Auto-generated by xml_to_header - do not edit\n";
    out << "#ifndef " << guard << "\n";
    out << "#define " << guard << "\n\n";
    out << "#include \"duilib/duilib_string.h\"\n\n";
    out << "namespace ui_resources {\n\n";

    for (const auto& fpath : inputFiles) {
        std::string content = readFile(fpath);
        if (content.empty()) return 1;

        std::string varName = "k_" + basenameNoExt(fpath);

        out << "// Original: " << fpath << "\n";
        out << "static const DString " << varName
            << " = _T(\"" << escapeString(content) << "\");\n\n";
    }

    out << "} // namespace ui_resources\n\n";
    out << "#endif // " << guard << "\n";

    std::cout << "Generated " << outputPath << " with "
              << inputFiles.size() << " XML files" << std::endl;
    return 0;
}
